# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "Integration"]
  pull_request:
    branches: [ "Integration" ]

jobs:
  Validate-essentials:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn -B test --file pom.xml

  Sonar:
     runs-on: ubuntu-latest
     needs: Validate-essentials
     if: github.event_name == 'push' #&& github.ref == 'refs/heads/Integration'
     steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: "21"
           distribution: "oracle"
           cache: 'maven'

       - name: SonarQube
         run: mvn clean verify -Pcoverage sonar:sonar -Dsonar.host.url=${{ secrets.SONARQUBE_URL }} -Dsonar.token=${{ secrets.SONARQUBE_TOKEN }} -Dsonar.projectKey=STEats-Team-L -Dsonar.projectName='STEats-Team-L'




